#!/usr/bin/env python3
"""Render synthetic narrated lecture videos and write eval labels from the known section times.

Uses macOS `say` for speech (falls back to `espeak-ng` if present) and ffmpeg for slides.
    python scripts/make_synthetic.py            # renders eval/videos/*.mp4 and eval/dataset.yaml
"""

import shutil
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "scripts/synth/lectures.yaml"
OUT = ROOT / "eval/videos"
DATASET = ROOT / "eval/dataset.yaml"
FONT = next(
    (p for p in ["/System/Library/Fonts/Supplemental/Arial.ttf", "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"] if Path(p).exists()),
    None,
)
PAD_S = 2.0
W, H = 1280, 720


def run(cmd: list[str]) -> None:
    subprocess.run(cmd, check=True, capture_output=True)


def tts(text: str, wav: Path) -> None:
    if shutil.which("say"):
        aiff = wav.with_suffix(".aiff")
        run(["say", "-o", str(aiff), text])
        run(["ffmpeg", "-y", "-v", "error", "-i", str(aiff), "-ac", "1", "-ar", "16000", str(wav)])
        aiff.unlink()
    elif shutil.which("espeak-ng"):
        run(["espeak-ng", "-w", str(wav), text])
    else:
        sys.exit("need macOS `say` or `espeak-ng` for narration")


def duration(path: Path) -> float:
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", str(path)],
        capture_output=True, text=True, check=True,
    ).stdout.strip()
    return float(out)


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace(":", "\\:").replace("'", "’").replace("%", "\\%")


def render_section(sec: dict, course: str, idx: int, total: int, work: Path) -> tuple[Path, float]:
    wav = work / f"s{idx}.wav"
    tts(sec["narration"].strip(), wav)
    dur = duration(wav) + PAD_S
    padded = work / f"s{idx}_pad.wav"
    run(["ffmpeg", "-y", "-v", "error", "-i", str(wav), "-af", f"apad=whole_dur={dur:.3f}", "-t", f"{dur:.3f}", str(padded)])
    draw = [
        f"drawtext=fontfile={FONT}:text='{esc(sec['title'])}':fontcolor=white:fontsize=64:x=80:y=90",
        f"drawtext=fontfile={FONT}:text='{esc(course)}':fontcolor=0xbbbbbb:fontsize=26:x=80:y=40",
        f"drawtext=fontfile={FONT}:text='{idx + 1} / {total}':fontcolor=0xbbbbbb:fontsize=26:x=w-tw-60:y=40",
    ]
    for j, b in enumerate(sec.get("bullets", [])):
        draw.append(f"drawtext=fontfile={FONT}:text='•  {esc(b)}':fontcolor=0xe8eaf0:fontsize=38:x=120:y={230 + j * 80}")
    mp4 = work / f"s{idx}.mp4"
    run(
        [
            "ffmpeg", "-y", "-v", "error",
            "-f", "lavfi", "-i", f"color=c={sec['color']}:size={W}x{H}:rate=25",
            "-i", str(padded), "-t", f"{dur:.3f}", "-vf", ",".join(draw),
            "-c:v", "libx264", "-preset", "veryfast", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest", str(mp4),
        ]
    )
    return mp4, dur


def main() -> None:
    spec = yaml.safe_load(SPEC.read_text())
    OUT.mkdir(parents=True, exist_ok=True)
    videos, queries = [], []
    for lec in spec["lectures"]:
        work = OUT / f".work_{lec['key']}"
        work.mkdir(exist_ok=True)
        parts, t = [], 0.0
        secs = lec["sections"]
        for i, sec in enumerate(secs):
            mp4, dur = render_section(sec, lec["course"], i, len(secs), work)
            parts.append(mp4)
            for k, q in enumerate(sec.get("queries", [])):
                queries.append(
                    {
                        "id": f"{lec['key']}.{i}.{k}", "text": q["text"], "modality": q.get("modality", "speech"),
                        "relevant": [{"video": lec["key"], "start_s": round(t, 2), "end_s": round(t + dur, 2)}],
                    }
                )
            t += dur
            print(f"  {lec['key']} section {i}: {sec['title']!r} {dur:.1f}s")
        lst = work / "list.txt"
        lst.write_text("".join(f"file '{p.name}'\n" for p in parts))
        final = OUT / f"{lec['key']}.mp4"
        run(["ffmpeg", "-y", "-v", "error", "-f", "concat", "-safe", "0", "-i", str(lst), "-c", "copy", str(final)])
        shutil.rmtree(work)
        videos.append({"key": lec["key"], "title": lec["title"], "file": f"eval/videos/{final.name}", "license": "synthetic (generated)"})
        print(f"wrote {final} ({t:.0f}s)")
    DATASET.write_text(
        "# Generated by scripts/make_synthetic.py. Add your own videos/queries below or in a separate file.\n"
        + yaml.safe_dump({"videos": videos, "queries": queries}, sort_keys=False, allow_unicode=True, width=120)
    )
    print(f"wrote {DATASET}: {len(videos)} videos, {len(queries)} queries")


if __name__ == "__main__":
    main()
